---
title: "Forecast ASMT 5"
output:
  html_document:
    df_print: paged
---

 
# Prepare data
## Load libraries 
```{r echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
library(janitor)
library(skimr)
library(kableExtra)
library(GGally)
library(vip)        
library(fastshap)   
library(MASS)
library(ISLR)
library(tree)
library(ggplot2)
library(dplyr)
library(lubridate)
library(imputeTS)
library(imputeTS)
library(forecast)
library(urca)
library(astsa)
library(fpp2)
```

## Load data and create TS
```{r}
sales <- read.csv("RetailSales2.csv")
sales$date <- as.Date(sales$date, format = "%d-%b-%y")
laces_ts <- ts(sales$laces, start = c(1994, 1), end = c(1998, 9), frequency = 12)
blouses_ts <- ts(sales$blouses, start = c(1994, 1), end = c(1998, 9), frequency = 12)

```

## plot TS and plot acf, pacf
```{r}
plot(laces_ts)
plot(blouses_ts)
ggAcf(laces_ts)
ggPacf(laces_ts)
ggAcf(blouses_ts)
ggPacf(blouses_ts)
```
# Fit model
## Fit seasonal exponential smoothing model - Laces
```{r}


laces_ets <- ets(laces_ts, model="ZNZ")
summary(laces_ets)
checkresiduals(laces_ets)

forecast(laces_ets, h=3)%>% autoplot()

# 5.693469

```

## Try Holt Winters - laces


```{r}

# Additive

HWA <- hw(laces_ts, seasonal="additive", h=3)
summary(HWA)
checkresiduals(HWA)
HWA %>% forecast(h=3)
HWA %>% forecast(h=3) %>% autoplot()
#MAPE 5.768398


# Multiplicative

HWM <- hw(laces_ts, seasonal="multiplicative", h=3)
summary(HWM)
checkresiduals(HWM)
HWM %>% forecast(h=3)
HWM %>% forecast(h=3) %>% autoplot()

#MAPe 5.940346

```
## Fit auto.ARIMA - Laces
```{r}
fit_auto <- auto.arima(laces_ts)
summary(fit_auto)
checkresiduals(fit_auto)
accuracy(fit_auto)

forecast(fit_auto, h=6)

fit_auto %>% forecast(h=3)
fit_auto %>% forecast(h=3) %>% autoplot()

```

# Comparing accuracy - laces

```{r}

pred_ses <- ts(c(8875.335,7212.041,7068.571), start = c(1998, 10), frequency = 12) #SES
pred_add <- ts(c(8901.989,7169.937,7085.806), start = c(1998, 10), frequency = 12) 
pred_arima <- ts(c(8164.143,6373.645,5722.811), start = c(1998, 10), frequency = 12) #auto.ARIMA

truth <- ts(c(9729.8 ,6576.2,6075.3), start = c(1998, 10), frequency = 12)

# blouses_true =  ts(c(28459 ,23251,22044), start = c(1998, 10), frequency = 12)

accuracy(pred_ses, truth)
accuracy(pred_add, truth)
accuracy(pred_arima, truth)
```
# Fit model
## Try Holt Winters - blouses


```{r}

# Additive

HWA <- hw(blouses_ts, seasonal="additive", h=3)
summary(HWA)
HWA %>% forecast(h=3)
HWA %>% forecast(h=3) %>% autoplot()
#MAPE 5.022268


# Multiplicative

HWM <- hw(blouses_ts, seasonal="multiplicative", h=3)
summary(HWM)
HWM %>% forecast(h=3)
HWM %>% forecast(h=3) %>% autoplot()

#mape 4.654127

```


## fit auto.arima 

```{r}

fit_auto2 <- auto.arima(blouses_ts)
summary(fit_auto2)
checkresiduals(fit_auto2)
accuracy(fit_auto2)





fit_auto2 %>% forecast(h=3)

# mape 4.280318


```
# Comparing accuracy - blouse

```{r}

pred_add <- ts(c(26279.63,20027.77,21147.82	), start = c(1998, 10), frequency = 12) #add
pred_mul <- ts(c(27534.00,19043.85,20905.34), start = c(1998, 10), frequency = 12) #mul
pred_arima <- ts(c(28501.79,19538.67,21345.41), start = c(1998, 10), frequency = 12) #auto.arima

truth <- ts(c(28459 ,23251,22044), start = c(1998, 10), frequency = 12)

# blouses_true =  ts(c(28459 ,23251,22044), start = c(1998, 10), frequency = 12)

accuracy(pred_add, truth)
accuracy(pred_mul, truth)
accuracy(pred_arima, truth)
```

